### ISSUE TITLE
can not download pretrain model through the provide website

### ISSUE THREAD

**Issue by NERO-S** [syguan96/BOA#1]
![image](https://user-images.githubusercontent.com/39329935/114870591-ee5fc180-9e2a-11eb-9def-ae3a5651c21a.png)

**Comment by gsygsygsy123** [comment]
Sorry for this mistake. I will revise the download link in the readme.
New download link: https://drive.google.com/file/d/1X2cky7_1StmzYinbcmzLHRT9YX5FMLL-/view?usp=sharing

**Comment by gsygsygsy123** [comment]
Sorry for this mistake. The new  download link: https://drive.google.com/file/d/1kpsCwT6DDtLUHP2IucSKEDxj9wB6vRHz/view?usp=sharing

I will revise it in the readme.

**Comment by syguan96** [comment]
I feel so sorry. This error is revised in the readme.
