### ISSUE TITLE
about 3DHP dataset

### ISSUE THREAD

**Issue by tszhang97** [syguan96/BOA#2]
About 3DHP dataset, did you use the SMPL data provided by SPIN (mpi-inf-3dhp_mview_fits.npz) or the final fits data (http://visiondata.cis.upenn.edu/spin/spin_fits.tar.gz)

**Comment by syguan96** [comment]
3DHP data is download from http://gvv.mpi-inf.mpg.de/3dhp-dataset/. I didn't use SMPL data or the fits.
