### ISSUE TITLE
Time and device to train the network?

### ISSUE THREAD

**Issue by wutherRRR** [syguan96/BOA#4]
Hello,

May I know what GPUs do you use and how long does it take to train the model?
Your reply would be much appreciated. Looking forward.

Thank you!

**Comment by syguan96** [comment]
Hi, I train my model on 2080 Ti. The BOA on 3DPW which has 35k images takes about 12 hours.
And we will release a faster version soon.

**Comment by wutherRRR** [comment]
Dear author,

Thank you very much for your prompt reply. 

I have one more question:
I did not find the training code. Am I misunderstanding or whether/when do you plan to release the code for training?

Thanks a lot in advance! Looking forward to trying out the training code.

**Comment by syguan96** [comment]
For the training code, you can refer to SPIN.

**Comment by wutherRRR** [comment]
Thank you for the reply!
