### ISSUE TITLE
SMPL+H

### ISSUE THREAD

**Issue by NoLookDefense** [syguan96/BOA#5]
Hi. Thanks for your great work. I wonder where to download SMPL+H model?

**Comment by syguan96** [comment]
You can download SMPL from this website:https://smpl.is.tue.mpg.de/

**Comment by NoLookDefense** [comment]
> You can download SMPL from this website:https://smpl.is.tue.mpg.de/

Thank you. I wonder SMPL+H and SMPL model are the same? I only know that SMPL-X is different from SMPL.

**Comment by syguan96** [comment]
If you only care about the keypoints of the body, they should be the same.

**Comment by NoLookDefense** [comment]
Could you kindly provide the SMPLH_GENDER.pkl  model during Google drive? I feel sorry that there are too many models in the website but I didn't find one with such a name.

**Comment by syguan96** [comment]
Download the pkl models, and then remove the chumpy dependencies. After that, rename the processed model to the corresponding name.

**Comment by NoLookDefense** [comment]
> Download the pkl models, and then remove the chumpy dependencies. After that, rename the processed model to the corresponding name.

Thank you. Actually I was trapped in the download step. Is the pkl models of SMPL+H downloaded from this link? But I can only see .npz files inside it. It's from https://mano.is.tue.mpg.de/downloads

![711625748184_ pic_hd](https://user-images.githubusercontent.com/81567453/124923682-47578400-e02d-11eb-9e8c-4369b16543b3.jpg)

**Comment by syguan96** [comment]
I think you can download what you want from this URL:https://psfiles.is.tuebingen.mpg.de/downloads/mano/mano_v1_2-zip

**Comment by l-mengwei** [comment]
> 

there are smplh_female.pkl and smplh_male.pkl in mano_vi_2.zip file, but no smplh_gender.pkl .would you tell me where is the smplh_gender.pkl  ?  
![图片](https://user-images.githubusercontent.com/90177116/159217936-e6578ff7-6a6b-475b-acf9-f560a64184a4.png)

**Comment by l-mengwei** [comment]
> I think you can download what you want from this URL:https://psfiles.is.tuebingen.mpg.de/downloads/mano/mano_v1_2-zip

there are smplh_female.pkl and smplh_male.pkl in mano_vi_2.zip file, but no smplh_gender.pkl .would you tell me where is the smplh_gender.pkl ?  Thans a lot.
![图片](https://user-images.githubusercontent.com/90177116/159218456-51ad6b5b-a448-4e2f-8729-e20b228c6fad.png)

**Comment by l-mengwei** [comment]
> Could you kindly provide the SMPLH_GENDER.pkl model during Google drive? I feel sorry that there are too many models in the website but I didn't find one with such a name.

Hello! did you solve it? would you tell me how smplh_gender.pkl file  was generated？thanks a lot !
